# .github/workflows/release.yml
name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux-x64
            binary: asteroid-dodger-linux-x64
          - os: ubuntu-20.04
            platform: linux-x64-compat
            binary: asteroid-dodger-linux-x64-compat
          - os: macos-latest
            platform: macos
            binary: asteroid-dodger-macos
          # Removed Windows since ncurses doesn't work there

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies (Ubuntu)
      if: contains(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses5-dev

    - name: Install dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install ncurses

    - name: Build game
      working-directory: ./terminal-game
      run: |
        make static
        cp bin/main ${{ matrix.binary }}

    - name: Test binary
      run: |
        file ${{ matrix.binary }}
        chmod +x ${{ matrix.binary }}
        ls -la ${{ matrix.binary }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.binary }}
        path: ./${{ matrix.binary }}

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./binaries

    - name: Display structure
      run: |
        echo "Downloaded artifacts:"
        find ./binaries -type f -name "asteroid-dodger-*"
        ls -la ./binaries/*/

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: ./binaries/*/asteroid-dodger-*
        draft: false
        prerelease: false
        generate_release_notes: true
        body: |
          🚀 **Terminal Asteroid Dodger Release ${{ github.ref_name }}**
          
          Download the appropriate binary for your system:
          - `asteroid-dodger-linux-x64` - Modern Linux 64-bit
          - `asteroid-dodger-linux-x64-compat` - Older Linux systems
          - `asteroid-dodger-macos` - macOS (Intel/Apple Silicon)
          
          **Quick Start:**
          ```bash
          # Linux/WSL users
          chmod +x asteroid-dodger-linux-x64
          ./asteroid-dodger-linux-x64
          
          # macOS users
          chmod +x asteroid-dodger-macos
          ./asteroid-dodger-macos
          ```
          
          **System Requirements:**
          - Terminal with 80x24 minimum size
          - Color support recommended
          - ncurses library (usually pre-installed)
          
          **Controls:**
          - WASD or Arrow Keys: Move ship
          - Q: Quit game
          - R: Restart after game over
          
          Enjoy dodging those asteroids! 🌟
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
